name: Linux_MultiContainer_Workflow

on:
  push:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Azure login
      - name: Sign in via Azure CLI
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Docker login to ACR using secrets
      - name: Azure Container Registry login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # Build & push each service
      - name: Build and push containers
        run: |
          docker build ./api -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/api:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/api:${{ github.sha }}

          docker pull redis:latest
          docker tag redis:latest ${{ secrets.REGISTRY_LOGIN_SERVER }}/redis:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/redis:${{ github.sha }}

          docker pull nginx:latest
          docker tag nginx:latest ${{ secrets.REGISTRY_LOGIN_SERVER }}/nginx:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/nginx:${{ github.sha }}

      # Deploy with safe startup command
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'AIAssignmentChecker'
          images: |
            ${{ secrets.REGISTRY_LOGIN_SERVER }}/redis:${{ github.sha }}
            ${{ secrets.REGISTRY_LOGIN_SERVER }}/api:${{ github.sha }}
            ${{ secrets.REGISTRY_LOGIN_SERVER }}/nginx:${{ github.sha }}
          startup-command: >
            docker network rm appnet || true &&
            docker network create appnet &&
            docker rm -f redis || true &&
            docker rm -f api || true &&
            docker rm -f worker1 || true &&
            docker rm -f worker2 || true &&
            docker rm -f nginx || true &&
            docker run -d --name redis --network appnet ${{ secrets.REGISTRY_LOGIN_SERVER }}/redis:${{ github.sha }} &&
            docker run -d --name api --network appnet -p 3000:3000 ${{ secrets.REGISTRY_LOGIN_SERVER }}/api:${{ github.sha }} &&
            docker run -d --name worker1 --network appnet ${{ secrets.REGISTRY_LOGIN_SERVER }}/api:${{ github.sha }} npm run workerdev &&
            docker run -d --name worker2 --network appnet ${{ secrets.REGISTRY_LOGIN_SERVER }}/api:${{ github.sha }} npm run workerdev &&
            docker run -d --name nginx --network appnet -p 80:80 ${{ secrets.REGISTRY_LOGIN_SERVER }}/nginx:${{ github.sha }}

      # Logout
      - name: Azure logout
        run: az logout
