# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - AIAssignmentChecker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: aiassigmentcheckerregistry.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_E49E92EC5D904C399EA8AA21DBBE5A4B }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_ECA73F259E804FEFBB1856B32A4F38BD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: aiassigmentcheckerregistry.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_E49E92EC5D904C399EA8AA21DBBE5A4B }}/api:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build
    

    steps:
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9E0A496B353C42958155C45640E28371 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F482998AD2DD400086601E98B4BCBF9F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_91C51CD449D549C090D796512AA2322C }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'AIAssignmentChecker'
          slot-name: 'Production'
          images: 'aiassigmentcheckerregistry.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_E49E92EC5D904C399EA8AA21DBBE5A4B }}/api:${{ github.sha }}'
          