# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - AIAssignmentChecker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: aiassigmentcheckerregistry.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_ADE3BA3136724D4FBE42C9A35C4279F9 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_929CE5EE396440C9BD006D618EA0D776 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: aiassigmentcheckerregistry.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_ADE3BA3136724D4FBE42C9A35C4279F9 }}/api:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build
    

    steps:
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A7BAC3485B3F43C885EFC795EC04F8A0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_494744169A95408592AC3A943A6C4ADD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F499292026B549CDAA46847BD6BBFA72 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'AIAssignmentChecker'
          slot-name: 'Production'
          images: 'aiassigmentcheckerregistry.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_ADE3BA3136724D4FBE42C9A35C4279F9 }}/api:${{ github.sha }}'
          